### ISSUE TITLE
"Unexpected end of file" / "Error in frame 2"

### ISSUE THREAD

**Issue by sebastien-plutniak** [tbvdm/sigbak#12]
Hi,

On (arch)linux 
`sigbak export-messages signal.backup messages` raises an error:
> sigbak: Unexpected end of file

and
`sigbak check-backup signal.backup` raises:
> sigbak: Unexpected end of file
> sigbak: Error in frame 2

Does the problem lies in my backup file? What other useful information may I give you?

Thank you in advance !

**Comment by tbvdm** [comment]
Hi. It is possible that your backup file has been truncated. Is your backup file larger than, say, 1 MB?

The other possibility is that the passphrase is incorrect. Are you sure you have the right passphrase?

**Comment by sebastien-plutniak** [comment]
Hi, my backup is much larger than 1 MO, it is more about 2.5 Go =)
Is that an issue for sigbak?

Yes, I think my passphrase is correct (if I change it, it raises a “MAC” error)

**Comment by tbvdm** [comment]
> Hi, my backup is much larger than 1 MO, it is more about 2.5 Go =)
> Is that an issue for sigbak?

No, that's fine. It simply means that we can rule out truncation.

> Yes, I think my passphrase is correct (if I change it, it raises a “MAC” error)

Unfortunately, that does not imply that the other passphrase is correct. :) Every invalid passphrase will produce an error, but the errors may be different.

Are you really sure your passphrase is correct? You can verify it in Signal: Settings > Chats > Chat backups > Verify backup passphrase.

**Comment by sebastien-plutniak** [comment]
Thanks, I've checked the passphrase and… you are right, it was wrong. With the correct passphrase it works well!
Sorry for that! I close the issue.
