### ISSUE TITLE
Cannot export messages

### ISSUE THREAD

**Issue by wdomski** [tbvdm/sigbak#19]
When running export-messages command I receive following:

"sigbak: Cannot execute SQL statement: error in tokenizer constructor"

**Comment by tbvdm** [comment]
What version of sqlite3 is sigbak linked against?

**Comment by wdomski** [comment]
The version of libsqlite3 is 3.22.0-1ubuntu0.7. I am building it on Ubuntu 18.04.

**Comment by wdomski** [comment]
Just tested on Ubuntu 22.04 with libsqlite3 version 3.37.2-2ubuntu0.3. Everything works as expected. Sorry for the confusion.

**Comment by tbvdm** [comment]
No problem. It appears that newer backups (starting from around August) need sqlite 3.25.0 or later.
