### ISSUE TITLE
can't compile on Linux Mint due to openssl/kdf.h: No such file or directory

### ISSUE THREAD

**Issue by jerkey** [tbvdm/sigbak#2]
i went down a rabbit hole trying to figure out why i don't have kdf.h (even though i have openssl) and I couldn't figure it out...this may be a result of my lack of knowledge on this stuff but i tried my best to resolve it.

sigbak/ $ make
cc   -c -o compat/hkdf.o compat/hkdf.c
compat/hkdf.c:22:25: fatal error: openssl/kdf.h: No such file or directory
compilation terminated.
Makefile:42: recipe for target 'compat/hkdf.o' failed
make: *** [compat/hkdf.o] Error 1

**Comment by tbvdm** [comment]
What's your OpenSSL version? You need 1.1.0 or higher.

**Comment by jerkey** [comment]
> What's your OpenSSL version? You need 1.1.0 or higher.

oh i have 1.0.2g-1ubuntu4.15 so that's probably the problem.  Thank you for the help!

I guess it says that right in the README :)

**Comment by tbvdm** [comment]
It turns out it's not so complicated to support OpenSSL 1.0.x. Could you try the openssl-1.0.x branch that I just pushed?
