### ISSUE TITLE
Problem building 'makefile:14: *** missing separator. Stop'

### ISSUE THREAD

**Issue by mscholzj** [tbvdm/sigbak#4]
hello, 

i have trouble building the program  due to the following error:

```bash
$ make
Makefile:14: *** Fehlender Trenner.  Schluss.
$ make install
Makefile:14: *** Fehlender Trenner.  Schluss.
```

I think the error roughly translates to the following:

`makefile:14: *** missing separator. Stop`
(https://stackoverflow.com/questions/16931770/makefile4-missing-separator-stop)

I try to build it in my virtual machine with the following os:

```
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
```

Could you please help me as i am new to Makefiles.

Btw. i have the same problem with `sigtop`.

**Comment by tbvdm** [comment]
It looks like you forgot to switch to the portable branch. Run the following command in the sigbak repository. You only have to run it once.

git checkout portable

And to fix your problem with sigtop, run the above command in the sigtop repository as well.

**Comment by mscholzj** [comment]
It works perfectly now. Thank you very much for the help and this tool!
