### ISSUE TITLE
Output quote references

### ISSUE THREAD

**Issue by zagl** [tbvdm/sigbak#5]
sigbak doesn't mark messages as quotes at the moment, does it?
Could this be implemented?

In text output format for a quoting message:
Quote: "the quoted message id"

**Comment by tbvdm** [comment]
sigbak doesn't handle quotes at all. I hadn't got round to it, but I'll have a look now.

**Comment by tbvdm** [comment]
Quotes are now shown in the text format. If there are any issues, let me know.

**Comment by zagl** [comment]
Very nice implementation. Thank you very much!

**Comment by tbvdm** [comment]
sigbak doesn't handle quotes at all. I hadn't got round to it, but I'll have a look now.
