### ISSUE TITLE
sigbak preferred over sigtop?

### ISSUE THREAD

**Issue by corbolais** [tbvdm/sigbak#7]
Hi Tim,

It would be helpful to distinguish sigbak and sigtop more clearly. ;-) It took me some back and forth to realize which is about what.

The file signal.backup, is this just the sql file copied over from your android phone? Can you provide instructions how to recuperate this file depending on android versions? The path and names have changed over time. A rooted android OS is required to access this file, as well.

Thank you for those tools! :)

Cheers.

**Comment by tbvdm** [comment]
Hi,

I had hoped that the very first sentence of the respective readmes would be sufficiently clear. If you have suggestions for improvement, I'd be happy to consider them.

The `signal.backup` filename refers to any backup file created by the Signal app. You can copy these backup files just like you would with other files on your phone. You don't need root privileges. See the [Signal documentation](https://support.signal.org/hc/en-us/articles/360007059752-Backup-and-Restore-Messages#android_enable) for more information.

**Comment by corbolais** [comment]
Hi,

:) That's what I thought after the fact. My suggestion is to just oppose the two: 

"sigbak" (this repository) is [...] as opposed to "sigtop" which is [...].

That woud've made it sufficiently clear *for me* in the first place.

Thank you for bringing to my attention the relevant Signal documentation.

cheers

**Comment by tbvdm** [comment]
I'll see if I can improve the phrasing. Thanks for bringing this up!
