### ISSUE TITLE
Attachment ids 

### ISSUE THREAD

**Issue by Leugimlra** [tbvdm/sigbak#9]
Hello! I'm trying to find a way to match up the attachment ids in the result of the export-messages command to the attachments that are a result of the export-attachments command. Is there a good way to do this?

**Comment by tbvdm** [comment]
I could add an option to prepend the attachment id to attachment filenames. Would that solve your problem?

**Comment by Leugimlra** [comment]
That would be perfect!

**Comment by tbvdm** [comment]
The new option is `-I`.
